-- 1. id_int en cada tabla: bigint, unico, autoincrementable
DO $do$
DECLARE
  r record;
  v_next bigint;
BEGIN
  FOR r IN
    SELECT * FROM (VALUES
      ('users','created_at, id'),
      ('plans','created_at, id'),
      ('message_packs','created_at, id'),
      ('purchases','created_at, id'),
      ('usage_balance','period_start, user_id'),
      ('whatsapp_connections','updated_at, id'),
      ('stripe_events','processed_at, id')
    ) AS t(tbl, ord)
  LOOP
    EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS id_int bigint', r.tbl);
    EXECUTE format(
      'UPDATE public.%1$I AS tgt SET id_int = s.rn FROM (SELECT ctid, row_number() OVER (ORDER BY %2$s) AS rn FROM public.%1$I) AS s WHERE s.ctid = tgt.ctid AND tgt.id_int IS NULL',
      r.tbl, r.ord);
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id_int SET NOT NULL', r.tbl);
    EXECUTE format('SELECT COALESCE(max(id_int), 0) + 1 FROM public.%I', r.tbl) INTO v_next;
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id_int ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)', r.tbl, v_next);
    EXECUTE format('ALTER TABLE public.%1$I ADD CONSTRAINT %1$s_id_int_key UNIQUE (id_int)', r.tbl);
  END LOOP;
END
$do$;

-- 2. Columnas FK numericas + backfill + FK + indice
ALTER TABLE public.users ADD COLUMN plan_id_int bigint;
UPDATE public.users u SET plan_id_int = p.id_int FROM public.plans p WHERE p.id = u.plan_id;
ALTER TABLE public.users
  ADD CONSTRAINT users_plan_id_int_fkey FOREIGN KEY (plan_id_int)
  REFERENCES public.plans(id_int) ON DELETE SET NULL;
CREATE INDEX users_plan_id_int_idx ON public.users (plan_id_int);

ALTER TABLE public.usage_balance ADD COLUMN user_id_int bigint;
UPDATE public.usage_balance b SET user_id_int = u.id_int FROM public.users u WHERE u.id = b.user_id;
ALTER TABLE public.usage_balance
  ADD CONSTRAINT usage_balance_user_id_int_fkey FOREIGN KEY (user_id_int)
  REFERENCES public.users(id_int) ON DELETE CASCADE;
CREATE INDEX usage_balance_user_id_int_idx ON public.usage_balance (user_id_int);

ALTER TABLE public.purchases ADD COLUMN user_id_int bigint;
ALTER TABLE public.purchases ADD COLUMN pack_id_int bigint;
UPDATE public.purchases pu SET user_id_int = u.id_int FROM public.users u WHERE u.id = pu.user_id;
UPDATE public.purchases pu SET pack_id_int = mp.id_int FROM public.message_packs mp WHERE mp.id = pu.pack_id;
ALTER TABLE public.purchases
  ADD CONSTRAINT purchases_user_id_int_fkey FOREIGN KEY (user_id_int)
  REFERENCES public.users(id_int) ON DELETE CASCADE;
ALTER TABLE public.purchases
  ADD CONSTRAINT purchases_pack_id_int_fkey FOREIGN KEY (pack_id_int)
  REFERENCES public.message_packs(id_int) ON DELETE SET NULL;
CREATE INDEX purchases_user_id_int_idx ON public.purchases (user_id_int);
CREATE INDEX purchases_pack_id_int_idx ON public.purchases (pack_id_int);

ALTER TABLE public.whatsapp_connections ADD COLUMN user_id_int bigint;
UPDATE public.whatsapp_connections w SET user_id_int = u.id_int FROM public.users u WHERE u.id = w.user_id;
ALTER TABLE public.whatsapp_connections
  ADD CONSTRAINT whatsapp_connections_user_id_int_fkey FOREIGN KEY (user_id_int)
  REFERENCES public.users(id_int) ON DELETE CASCADE;
CREATE INDEX whatsapp_connections_user_id_int_idx ON public.whatsapp_connections (user_id_int);

-- 3. Triggers que derivan las FK numericas desde el UUID
CREATE OR REPLACE FUNCTION public.sync_users_plan_id_int()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $fn$
BEGIN
  IF NEW.plan_id IS NULL THEN
    NEW.plan_id_int := NULL;
  ELSIF NEW.plan_id_int IS NULL OR NEW.plan_id IS DISTINCT FROM COALESCE(OLD.plan_id, NULL) THEN
    SELECT p.id_int INTO NEW.plan_id_int FROM public.plans p WHERE p.id = NEW.plan_id;
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE TRIGGER users_sync_plan_id_int
BEFORE INSERT OR UPDATE ON public.users
FOR EACH ROW EXECUTE FUNCTION public.sync_users_plan_id_int();

CREATE OR REPLACE FUNCTION public.sync_user_id_int()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $fn$
BEGIN
  IF NEW.user_id IS NOT NULL AND NEW.user_id_int IS NULL THEN
    SELECT u.id_int INTO NEW.user_id_int FROM public.users u WHERE u.id = NEW.user_id;
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE TRIGGER usage_balance_sync_user_id_int
BEFORE INSERT OR UPDATE ON public.usage_balance
FOR EACH ROW EXECUTE FUNCTION public.sync_user_id_int();

CREATE TRIGGER whatsapp_connections_sync_user_id_int
BEFORE INSERT OR UPDATE ON public.whatsapp_connections
FOR EACH ROW EXECUTE FUNCTION public.sync_user_id_int();

CREATE OR REPLACE FUNCTION public.sync_purchases_ids_int()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $fn$
BEGIN
  IF NEW.user_id IS NOT NULL AND NEW.user_id_int IS NULL THEN
    SELECT u.id_int INTO NEW.user_id_int FROM public.users u WHERE u.id = NEW.user_id;
  END IF;
  IF NEW.pack_id IS NULL THEN
    NEW.pack_id_int := NULL;
  ELSIF NEW.pack_id_int IS NULL THEN
    SELECT mp.id_int INTO NEW.pack_id_int FROM public.message_packs mp WHERE mp.id = NEW.pack_id;
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE TRIGGER purchases_sync_ids_int
BEFORE INSERT OR UPDATE ON public.purchases
FOR EACH ROW EXECUTE FUNCTION public.sync_purchases_ids_int();
