/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EsIndexRouteImport } from './routes/es/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EsPreciosRouteImport } from './routes/es/precios'
import { Route as EsGuiaRouteImport } from './routes/es/guia'
import { Route as EsFaqRouteImport } from './routes/es/faq'
import { Route as EsContactoRouteImport } from './routes/es/contacto'
import { Route as EnWhatsappSetupGuideRouteImport } from './routes/en/whatsapp-setup-guide'
import { Route as EnPricingRouteImport } from './routes/en/pricing'
import { Route as EnFaqRouteImport } from './routes/en/faq'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicWhatsappConnectionsUpsertRouteImport } from './routes/api/public/whatsapp/connections/upsert'
import { Route as ApiPublicWhatsappConnectionsStatusRouteImport } from './routes/api/public/whatsapp/connections/status'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsPreciosRoute = EsPreciosRouteImport.update({
  id: '/es/precios',
  path: '/es/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const EsGuiaRoute = EsGuiaRouteImport.update({
  id: '/es/guia',
  path: '/es/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const EsFaqRoute = EsFaqRouteImport.update({
  id: '/es/faq',
  path: '/es/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EsContactoRoute = EsContactoRouteImport.update({
  id: '/es/contacto',
  path: '/es/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EnWhatsappSetupGuideRoute = EnWhatsappSetupGuideRouteImport.update({
  id: '/en/whatsapp-setup-guide',
  path: '/en/whatsapp-setup-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPricingRoute = EnPricingRouteImport.update({
  id: '/en/pricing',
  path: '/en/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EnFaqRoute = EnFaqRouteImport.update({
  id: '/en/faq',
  path: '/en/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappConnectionsUpsertRoute =
  ApiPublicWhatsappConnectionsUpsertRouteImport.update({
    id: '/api/public/whatsapp/connections/upsert',
    path: '/api/public/whatsapp/connections/upsert',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappConnectionsStatusRoute =
  ApiPublicWhatsappConnectionsStatusRouteImport.update({
    id: '/api/public/whatsapp/connections/status',
    path: '/api/public/whatsapp/connections/status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/guia': typeof GuiaRoute
  '/precios': typeof PreciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/whatsapp-setup-guide': typeof EnWhatsappSetupGuideRoute
  '/es/contacto': typeof EsContactoRoute
  '/es/faq': typeof EsFaqRoute
  '/es/guia': typeof EsGuiaRoute
  '/es/precios': typeof EsPreciosRoute
  '/en/': typeof EnIndexRoute
  '/es/': typeof EsIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/whatsapp/connections/status': typeof ApiPublicWhatsappConnectionsStatusRoute
  '/api/public/whatsapp/connections/upsert': typeof ApiPublicWhatsappConnectionsUpsertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/guia': typeof GuiaRoute
  '/precios': typeof PreciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/whatsapp-setup-guide': typeof EnWhatsappSetupGuideRoute
  '/es/contacto': typeof EsContactoRoute
  '/es/faq': typeof EsFaqRoute
  '/es/guia': typeof EsGuiaRoute
  '/es/precios': typeof EsPreciosRoute
  '/en': typeof EnIndexRoute
  '/es': typeof EsIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/whatsapp/connections/status': typeof ApiPublicWhatsappConnectionsStatusRoute
  '/api/public/whatsapp/connections/upsert': typeof ApiPublicWhatsappConnectionsUpsertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/guia': typeof GuiaRoute
  '/precios': typeof PreciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/en/contact': typeof EnContactRoute
  '/en/faq': typeof EnFaqRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/whatsapp-setup-guide': typeof EnWhatsappSetupGuideRoute
  '/es/contacto': typeof EsContactoRoute
  '/es/faq': typeof EsFaqRoute
  '/es/guia': typeof EsGuiaRoute
  '/es/precios': typeof EsPreciosRoute
  '/en/': typeof EnIndexRoute
  '/es/': typeof EsIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/whatsapp/connections/status': typeof ApiPublicWhatsappConnectionsStatusRoute
  '/api/public/whatsapp/connections/upsert': typeof ApiPublicWhatsappConnectionsUpsertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacto'
    | '/faq'
    | '/guia'
    | '/precios'
    | '/sitemap.xml'
    | '/dashboard'
    | '/en/contact'
    | '/en/faq'
    | '/en/pricing'
    | '/en/whatsapp-setup-guide'
    | '/es/contacto'
    | '/es/faq'
    | '/es/guia'
    | '/es/precios'
    | '/en/'
    | '/es/'
    | '/api/public/stripe/webhook'
    | '/api/public/whatsapp/connections/status'
    | '/api/public/whatsapp/connections/upsert'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacto'
    | '/faq'
    | '/guia'
    | '/precios'
    | '/sitemap.xml'
    | '/dashboard'
    | '/en/contact'
    | '/en/faq'
    | '/en/pricing'
    | '/en/whatsapp-setup-guide'
    | '/es/contacto'
    | '/es/faq'
    | '/es/guia'
    | '/es/precios'
    | '/en'
    | '/es'
    | '/api/public/stripe/webhook'
    | '/api/public/whatsapp/connections/status'
    | '/api/public/whatsapp/connections/upsert'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contacto'
    | '/faq'
    | '/guia'
    | '/precios'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/en/contact'
    | '/en/faq'
    | '/en/pricing'
    | '/en/whatsapp-setup-guide'
    | '/es/contacto'
    | '/es/faq'
    | '/es/guia'
    | '/es/precios'
    | '/en/'
    | '/es/'
    | '/api/public/stripe/webhook'
    | '/api/public/whatsapp/connections/status'
    | '/api/public/whatsapp/connections/upsert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  FaqRoute: typeof FaqRoute
  GuiaRoute: typeof GuiaRoute
  PreciosRoute: typeof PreciosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EnContactRoute: typeof EnContactRoute
  EnFaqRoute: typeof EnFaqRoute
  EnPricingRoute: typeof EnPricingRoute
  EnWhatsappSetupGuideRoute: typeof EnWhatsappSetupGuideRoute
  EsContactoRoute: typeof EsContactoRoute
  EsFaqRoute: typeof EsFaqRoute
  EsGuiaRoute: typeof EsGuiaRoute
  EsPreciosRoute: typeof EsPreciosRoute
  EnIndexRoute: typeof EnIndexRoute
  EsIndexRoute: typeof EsIndexRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicWhatsappConnectionsStatusRoute: typeof ApiPublicWhatsappConnectionsStatusRoute
  ApiPublicWhatsappConnectionsUpsertRoute: typeof ApiPublicWhatsappConnectionsUpsertRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/precios': {
      id: '/es/precios'
      path: '/es/precios'
      fullPath: '/es/precios'
      preLoaderRoute: typeof EsPreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/guia': {
      id: '/es/guia'
      path: '/es/guia'
      fullPath: '/es/guia'
      preLoaderRoute: typeof EsGuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/faq': {
      id: '/es/faq'
      path: '/es/faq'
      fullPath: '/es/faq'
      preLoaderRoute: typeof EsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/contacto': {
      id: '/es/contacto'
      path: '/es/contacto'
      fullPath: '/es/contacto'
      preLoaderRoute: typeof EsContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/whatsapp-setup-guide': {
      id: '/en/whatsapp-setup-guide'
      path: '/en/whatsapp-setup-guide'
      fullPath: '/en/whatsapp-setup-guide'
      preLoaderRoute: typeof EnWhatsappSetupGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/pricing': {
      id: '/en/pricing'
      path: '/en/pricing'
      fullPath: '/en/pricing'
      preLoaderRoute: typeof EnPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/faq': {
      id: '/en/faq'
      path: '/en/faq'
      fullPath: '/en/faq'
      preLoaderRoute: typeof EnFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/connections/upsert': {
      id: '/api/public/whatsapp/connections/upsert'
      path: '/api/public/whatsapp/connections/upsert'
      fullPath: '/api/public/whatsapp/connections/upsert'
      preLoaderRoute: typeof ApiPublicWhatsappConnectionsUpsertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/connections/status': {
      id: '/api/public/whatsapp/connections/status'
      path: '/api/public/whatsapp/connections/status'
      fullPath: '/api/public/whatsapp/connections/status'
      preLoaderRoute: typeof ApiPublicWhatsappConnectionsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  FaqRoute: FaqRoute,
  GuiaRoute: GuiaRoute,
  PreciosRoute: PreciosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EnContactRoute: EnContactRoute,
  EnFaqRoute: EnFaqRoute,
  EnPricingRoute: EnPricingRoute,
  EnWhatsappSetupGuideRoute: EnWhatsappSetupGuideRoute,
  EsContactoRoute: EsContactoRoute,
  EsFaqRoute: EsFaqRoute,
  EsGuiaRoute: EsGuiaRoute,
  EsPreciosRoute: EsPreciosRoute,
  EnIndexRoute: EnIndexRoute,
  EsIndexRoute: EsIndexRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicWhatsappConnectionsStatusRoute:
    ApiPublicWhatsappConnectionsStatusRoute,
  ApiPublicWhatsappConnectionsUpsertRoute:
    ApiPublicWhatsappConnectionsUpsertRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
